title: Cybersecurity Portfolio
description: Pereowei Geku - Cybersecurity Professional
author: Pereowei Geku
theme: jekyll-theme-cayman
github_username: thelordpere
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
```
